FROM centos:7
#Dockerfile for logstash

USER root

RUN \
  yum update -y --quiet && \
  yum install -y --quiet wget && \
  yum install -y --quiet tar && \
  yum install -y --quiet which && \
  yum install -y --quiet java-1.8.0-openjdk && \
  yum install -y --quiet java-1.8.0-openjdk-devel

# Add a logstash user that LS will actually run as.
RUN groupadd -g 1000 logstash && \
    adduser -u 1000 -g 1000 -d /usr/share/logstash logstash
WORKDIR /usr/share/logstash

# Set up /local for the LS binaries and data.
RUN \
  mkdir -p /local/logstash && \
  chown logstash:logstash /local/logstash && \
  mkdir -p /local/data && \
  chown logstash:logstash /local/data

# Switch to the LS user. None of the rest needs root access.
USER logstash

# Set some ENV variables to cut down on the typos.
ENV LS_HOME /local/logstash
ENV LS_CONFIG /local/logstash/config/logstash.yml

# Pull Logstash down from ES.org, expand it and move it into place
RUN \
  cd /tmp && \
  wget --quiet https://www.elastic.co/downloads/logstash-oss/logstash-oss-7.10.0-linux-x86_64.tar.gz && \
  tar xfz logstash-oss-7.10.0-linux-x86_64.tar.gz && \
  rm -f logstash-oss-7.10.0-linux-x86_64.tar.gz && \
  mv /tmp/logstash-7.10.0/* /local/logstash

VOLUME ["/local/data"]

# Define the LS config to point our data to the volume.
RUN \
  mkdir -p $LS_HOME/config && \
  touch $LS_CONFIG && \
  printf "path:\n" >> $LS_CONFIG && \
  printf "  data: /local/data/data\n" >> $LS_CONFIG && \
  printf "  logs: /local/data/logs\n" >> $LS_CONFIG && \
  printf "  plugins: /local/data/plugins\n" >> $LS_CONFIG && \
  printf "  work: /local/data/work\n" >> $LS_CONFIG


# Ports to expose
EXPOSE 5044

# What we run by default
CMD bin/logstash -f logstash.conf
