FROM centos:7
#Dockerfile for elasticsearch 7.10.2 oss version

USER root

RUN \
  yum -y update && \
  yum -y install wget && \
  yum -y install tar && \
  yum -y install which && \
  yum -y remove bind-license
#  yum -y install java-1.8.0-openjdk && \
#  yum -y install java-1.8.0-openjdk-devel

# Add an elasticsearch user that ES will actually run as.
RUN groupadd -g 3333 elasticsearch && \
    adduser -u 3333 -g 3333 -d /usr/share/elasticsearch elasticsearch
WORKDIR /usr/share/elasticsearch

# Set up /local for the ES binaries and data.
RUN \
  mkdir -p /var/elasticsearch && \
  chown elasticsearch:elasticsearch /var/elasticsearch && \
  mkdir -p /usr/share/elasticsearch && \
  chown elasticsearch:elasticsearch /usr/share/elasticsearch

# Switch to the ES user. None of the rest needs root access.
USER elasticsearch

# Set some ENV variables to cut down on the typos.
ENV ES_HOME /usr/share/elasticsearch
ENV ES_CONFIG /usr/share/elasticsearch/config/elasticsearch.yml

# Pull Elasticsearch down from ES.org, expand it and move it into place
RUN \
  cd /tmp && \
  wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-7.10.2-linux-x86_64.tar.gz && \
  tar xfz elasticsearch-oss-7.10.2-linux-x86_64.tar.gz && \
  rm -f elasticsearch-oss-7.10.2-linux-x86_64.tar.gz && \
  mv /tmp/elasticsearch-7.10.2/* /usr/share/elasticsearch && \
  rmdir /tmp/elasticsearch-7.10.2 && \
  mkdir /usr/share/elasticsearch/data && \
  chown elasticsearch:elasticsearch /usr/share/elasticsearch/data

VOLUME ["/usr/share/elasticsearch/data"]

# Define the ES config to point our data to the volume.
RUN \
  printf "path:\n" >> $ES_CONFIG && \
  printf "  data: /usr/share/elasticsearch/data\n" >> $ES_CONFIG && \
  printf "  logs: /usr/share/elasticsearch/logs\n" >> $ES_CONFIG

# Ports to expose
# NOTE! ES doesn't have any authentication by default. It's probably a bad idea
# to EXPOSE these ports without some proxy, or outside of other Docker containers
EXPOSE 9200
EXPOSE 9300

# What we run by default
CMD ["/usr/share/elasticsearch/bin/elasticsearch"]
