FROM centos:7
#Dockerfile for filebeat 7.10.2 oss version
#filebeat runs as root
USER root

RUN \
  yum update -y && \
  yum install -y wget && \
  yum install -y tar && \
  yum install -y which && \
  yum -y remove bind-license

WORKDIR /usr/share/filebeat

RUN \
  mkdir -p /usr/share/filebeat/data && \
  mkdir -p /usr/share/filebeat/logs

# Pull Filebeat down from ES.org, expand it and move it into place
RUN \
  cd /tmp && \
  wget --quiet https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-oss-7.10.2-linux-x86_64.tar.gz && \
  tar xfz filebeat-oss-7.10.2-linux-x86_64.tar.gz && \
  rm -f filebeat-oss-7.10.2-linux-x86_64.tar.gz && \
  mv /tmp/filebeat-7.10.2-*/* /usr/share/filebeat && \
  rm -rf /tmp/filebeat-7.10.2-*

# What we run by default
CMD ["./filebeat"]
